Repository Sitecore/docker-images, pull requests merged in 2020-04, with the labels that each got.

#275 Override Publishing Service RootUrl setting to fix publishing
  windows/9.x.x/sitecore-ps-jss/Dockerfile
  windows/9.x.x/sitecore-ps-jss/config/PublishingService.config
  windows/9.x.x/sitecore-ps/Dockerfile
  windows/9.x.x/sitecore-ps/config/PublishingService.config
  windows/9.x.x/sitecore-sxa-ps-jss/Dockerfile
  windows/9.x.x/sitecore-sxa-ps-jss/config/PublishingService.config
  windows/9.x.x/sitecore-sxa-ps/Dockerfile
  windows/9.x.x/sitecore-sxa-ps/config/PublishingService.config
  windows/9.x.x/sitecore-xc-ps/Dockerfile
  windows/9.x.x/sitecore-xc-ps/config/PublishingService.config
Labels: QA running, bug

#261 #256: Add IsolationMode parameter to build.ps1
  Build.ps1
  modules/SitecoreImageBuilder/1.0.0/Public/Invoke-Build.ps1
Labels: QA running, on-hold

#300 Linux images 9.3 XP
  Build.ps1
  CHANGELOG.md
  IMAGES.md
  README.md
  linux/9.3.x/sitecore-spe-sql/Dockerfile
  linux/9.3.x/sitecore-spe-sql/attach-databases.sh
  linux/9.3.x/sitecore-spe-sql/build.json
  linux/9.3.x/sitecore-spe-sql/install-databases.sh
  linux/9.3.x/sitecore-sxa-sql/Dockerfile
  linux/9.3.x/sitecore-sxa-sql/attach-databases.sh
  linux/9.3.x/sitecore-sxa-sql/build.json
  linux/9.3.x/sitecore-sxa-sql/install-databases.sh
  linux/9.3.x/sitecore-xp-sql/Dockerfile
  linux/9.3.x/sitecore-xp-sql/attach-databases.sh
  linux/9.3.x/sitecore-xp-sql/boot.sh
  linux/9.3.x/sitecore-xp-sql/build.json
  linux/9.3.x/sitecore-xp-sql/install-databases.sh
Labels: enhancement

#301 FIX: chmod after copy
  linux/9.3.x/sitecore-spe-sql/Dockerfile
  linux/9.3.x/sitecore-sxa-sql/Dockerfile
Labels: bug
